ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'COURIER';

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "lat" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "lng" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "courierId" TEXT;

CREATE INDEX IF NOT EXISTS "Order_courierId_idx" ON "Order"("courierId");
CREATE INDEX IF NOT EXISTS "Order_status_idx" ON "Order"("status");
