services:
  - type: web
    name: nurov-marketplace
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SAMESITE
        value: lax
      - key: NEXT_PUBLIC_API_URL
        value: ""
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
